version: '3'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - URL=starovoytovai.ru
      - SUBDOMAINS=cloud,torrent,vw,hub,media,mail,wiki
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - EMAIL=stewk6@gmail.com
    volumes:
      - /swag_data:/config
      - /opt/jellyfin:/jellyfin
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/authelia_data:/config
    restart: unless-stopped
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    #ports:
    #  - 8080:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck: 
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    container_name: vaultwarden
    restart: always
    env_file:
      - vw.env
    ports:
      - 39299:80
    volumes:
      - /vw-data:/data
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /opt/heimdall_data:/config
        #ports:
        # - 80:80
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=
      - PASS=
      - WHITELIST=
      - HOST_WHITELIST=
    volumes:
      - /var/transmission/config:/config
      - /torrent/downloads:/downloads
      - /torrent/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  typemill:
    build: ./typemill-docker/
    container_name: typemill
    environment:
      - TYPEMILL_UID=1000
      - TYPEMILL_GID=1000
    volumes:
      - /var/typemill/:/var/www/html/
    restart: unless-stopped
