version: '3'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - URL=starovoytovai.ru
      - SUBDOMAINS=cloud,torrent,vw,media,wiki,manga,todo,git,music
        # - EXTRA_DOMAINS=cloud.starovoytovai.ru,torrent.starovoytovai.ru,vw.starovoytovai.ru,media.starovoytovai.ru,wiki.starovoytovai.ru,manga.starovoytovai.ru,todo.starovoytovai.ru,git.starovoytovai.ru
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - EMAIL=stewk6@gmail.com
    volumes:
      - /var/swag/:/config
      - /torrent/downloads/complete:/torrent/downloads/complete
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/authelia_data:/config
    restart: unless-stopped
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    #ports:
    #  - 8080:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck: 
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /var/owncloud/files:/mnt/data

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/owncloud/mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/owncloud/redis:/data
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    container_name: vaultwarden
    restart: always
    env_file:
      - vw.env
    volumes:
      - /var/vaultwarden:/data
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=
      - PASS=
      - WHITELIST=
      - HOST_WHITELIST=
    volumes:
      - /var/transmission/config:/config
      - /torrent/downloads:/downloads
      - /torrent/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  komga:
    image: gotson/komga:0.x
    container_name: komga
    volumes:
      - /var/komga/config:/config
      - /var/komga/data:/data
      - /etc/timezone:/etc/timezone
    user: "1000:1000"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
    restart: unless-stopped
  vikunja_db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: vikunja_db
    environment:
      MYSQL_ROOT_PASSWORD: ${VIKUNJA_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${VIKUNJA_MYSQL_USER}
      MYSQL_PASSWORD: ${VIKUNJA_MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - /var/vikunja/db:/var/lib/mysql
    restart: unless-stopped
  vikunja_api:
    image: vikunja/api
    container_name: vikunja_api
    environment:
      VIKUNJA_DATABASE_HOST: vikunja_db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${VIKUNJA_MYSQL_USER}
      VIKUNJA_DATABASE_DATABASE: vikunja
    # ports:
    #   - 3456:3456
    volumes:
      - /var/vikunja/files:/app/vikunja/files
    depends_on:
      - vikunja_db
    restart: unless-stopped
  vikunja_frontend:
    image: vikunja/frontend
    container_name: vikunja_frontend
    # ports:
    #   - 80:80
    # environment:
    #   VIKUNJA_API_URL: http://<your-ip-here>:3456/api/v1
    restart: unless-stopped
  gitea:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea_db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - 127.0.0.1:2222:22
    volumes:
      - /var/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    depends_on:
      - gitea_db
  gitea_db:
    image: mysql:8
    restart: unless-stopped
    container_name: gitea_db
    environment:
      - MYSQL_ROOT_PASSWORD=${GITEA_DB_ROOT_PASSWORD}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${GITEA_DB_PASSWORD}
      - MYSQL_DATABASE=gitea
    volumes:
      - /var/gitea_db/mysql:/var/lib/mysql
